core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }

delete_unused_files:
    path:     /deleteunusedfiles
    methods: [POST]
    defaults: { _controller: CoreBundle:Default:postDeleteUnusedFile }

upload:
    path:     /upload
    methods: [POST]
    defaults: { _controller: CoreBundle:Default:postUpload }

post_login:
    path:     /login
    methods: [POST]
    defaults: { _controller: CoreBundle:Security:postLogin }

post_logout:
    path:     /logout
    methods: [DELETE]
    defaults: { _controller: CoreBundle:Security:deleteLogout }

get_connected:
    path:     /connected
    methods: [GET]
    defaults: { _controller: CoreBundle:Security:getConnected }

get_google:
    path:     /googleredirect
    methods: [GET]
    defaults: { _controller: CoreBundle:Security:getGoogleRedirect }

post_google:
    path:     /googlelogin
    methods: [POST]
    defaults: { _controller: CoreBundle:Security:postGoogleLogin }

users:
    type:     rest
    resource: CoreBundle\Controller\UserController

tabs:
    type:     rest
    resource: CoreBundle\Controller\User\TabController

achievements:
    type:     rest
    resource: CoreBundle\Controller\User\AchievementController
