services:
    core.security.requestListener:
        class: CoreBundle\Security\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
