CoreBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50
        tabs:
            - Valid: ~

CoreBundle\Entity\Tab:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        color:
            - NotBlank: ~
            - Type: string
        orderNumber:
            - NotBlank: ~
            - Type: integer
        icon:
            - NotBlank: ~
            - Type: string
        achievements:
            - Valid: ~

CoreBundle\Entity\Achievement:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        color:
            - NotBlank: ~
            - Type: string
        order:
            - NotBlank: ~
            - Type: integer
        icon:
            - NotBlank: ~
            - Type: string
        favorite:
            - NotBlank: ~
            - Type: bool
        shortdesc:
            - NotBlank: ~
            - Type: string
        longdesc:
            - NotBlank: ~
            - Type: string

CoreBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string
