CoreBundle\Entity\Tab:
    exclusion_policy: none
    properties:
        id:
            groups: ['tab', 'user', 'achievement']
        name:
            groups: ['tab', 'user', 'post', 'achievement']
        color:
            groups: ['tab', 'user', 'post', 'achievement']
        orderNumber:
            groups: ['tab', 'user', 'post', 'achievement']
        icon:
            groups: ['tab', 'user', 'post', 'achievement']
        achievements:
            groups: ['tab', 'user', 'post']
        user:
            groups: ['tab', 'achievement']

