CoreBundle\Entity\User:
    exclusion_policy: none
    virtual_properties:
        getProfilePictureWebPath:
            serialized_name: profilePicturePath
            type: string
            groups: ['user', 'tab', 'achievement', 'post', 'search']
    properties:
        id:
            groups: ['user', 'tab', 'achievement', 'search']
        firstname:
            groups: ['user', 'tab', 'post', 'achievement', 'search']
        lastname:
            groups: ['user', 'tab', 'post', 'achievement', 'search']
        email:
            groups: ['user', 'tab', 'post', 'achievement', 'search']
        plainPassword:
            groups: ['post']
        tabs:
            groups: ['user']
        profilePicture:
            exclude: true
        nbAchievements:
            groups: ['user', 'tab', 'achievement', 'post']
