CoreBundle\Entity\User:
    exclusion_policy: none
    properties:
        id:
            groups: ['user', 'tab', 'achievement']
        firstname:
            groups: ['user', 'tab', 'post', 'achievement']
        lastname:
            groups: ['user', 'tab', 'post', 'achievement']
        email:
            groups: ['user', 'tab', 'post', 'achievement']
        plainPassword:
            groups: ['post']
        tabs:
            groups: ['user']
        profilePicture:
            groups: ['user', 'tab', 'achievement', 'post']
